[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vm_doc_input = "8FBdK1WvpGhnkgMVspcD1ocdZdVJhkYTBUGqtkSUvG1z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hieu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
